server:
  port: 8001

spring:
  cloud:
    config:
      server:
        svn:
          uri: http://10.1.15.50/AML/trunk/code/aml-server/src/main/
          username: jiamingyang
          password: 12345678
        default-label: resources
  profiles:
    active: subversion
  application:
    name: spring-cloud-config-server