server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiamy1227/spring-cloud-examples/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: jiamy1227                                             # git仓库的账号
          password: 59jiaJMY                                            # git仓库的密码